In [85]:
import pandas as pd

In [99]:
df = pd.read_excel('kobe_AdjShoot.xls')

In [100]:
df

,Season,Age,Tm,Lg,Pos,G,MP,FG,2P,3P,...,FTr,3PAr,FG.1,2P.1,3P.1,eFG.1,FT.1,TS.1,FTr.1,3PAr.1
0,1996-97,18,LAL,NBA,SF,71,1103,0.417,0.437,0.375,...,0.393,0.322,0.455,0.480,0.360,0.493,0.738,0.536,0.320,0.212
1,1997-98,19,LAL,NBA,SF,79,2056,0.428,0.456,0.341,...,0.501,0.241,0.450,0.470,0.346,0.478,0.737,0.524,0.330,0.159
2,1998-99,20,LAL,NBA,SG,50,1896,0.465,0.494,0.267,...,0.375,0.130,0.437,0.457,0.339,0.466,0.728,0.511,0.330,0.168
3,1999-00,21,LAL,NBA,SG,66,2524,0.468,0.489,0.319,...,0.341,0.122,0.449,0.468,0.353,0.478,0.750,0.523,0.308,0.167
4,2000-01,22,LAL,NBA,SG,68,2783,0.464,0.489,0.305,...,0.369,0.132,0.443,0.461,0.354,0.473,0.748,0.518,0.309,0.170
5,2001-02,23,LAL,NBA,SG,80,3063,0.469,0.489,0.250,...,0.369,0.083,0.445,0.465,0.354,0.477,0.752,0.520,0.293,0.181
6,2002-03,24,LAL,NBA,SG,82,3401,0.451,0.465,0.383,...,0.371,0.168,0.442,0.463,0.349,0.474,0.758,0.519,0.302,0.182
7,2003-04,25,LAL,NBA,SG,65,2447,0.438,0.463,0.327,...,0.452,0.184,0.439,0.460,0.347,0.471,0.752,0.516,0.303,0.187
8,2004-05,26,LAL,NBA,SG,66,2689,0.433,0.472,0.339,...,0.502,0.292,0.447,0.470,0.356,0.482,0.756,0.529,0.324,0.196
9,2005-06,27,LAL,NBA,SG,80,3277,0.450,0.482,0.347,...,0.377,0.238,0.454,0.478,0.358,0.490,0.745,0.536,0.333,0.202
10,2006-07,28,LAL,NBA,SG,77,3140,0.463,0.497,0.344,...,0.437,0.227,0.458,0.485,0.358,0.496,0.752,0.541,0.327,0.213
11,2007-08,29,LAL,NBA,SG,82,3192,0.459,0.490,0.361,...,0.439,0.246,0.457,0.484,0.362,0.497,0.755,0.540,0.306,0.222
12,2008-09,30,LAL,NBA,SG,82,2960,0.467,0.496,0.351,...,0.329,0.196,0.459,0.485,0.367,0.500,0.771,0.544,0.306,0.224
13,2009-10,31,LAL,NBA,SG,73,2835,0.456,0.487,0.329,...,0.345,0.192,0.461,0.492,0.355,0.501,0.759,0.543,0.300,0.222
14,2010-11,32,LAL,NBA,SG,82,2779,0.451,0.487,0.323,...,0.356,0.217,0.459,0.487,0.358,0.498,0.763,0.541,0.300,0.222
15,2011-12,33,LAL,NBA,SG,58,2232,0.430,0.464,0.303,...,0.338,0.215,0.448,0.477,0.349,0.487,0.752,0.527,0.276,0.226
16,2012-13,34,LAL,NBA,SG,78,3013,0.463,0.510,0.324,...,0.392,0.255,0.453,0.483,0.359,0.496,0.753,0.535,0.270,0.243
17,2013-14,35,LAL,NBA,SG,6,177,0.425,0.491,0.188,...,0.288,0.219,0.454,0.488,0.360,0.501,0.756,0.541,0.284,0.259
18,2014-15,36,LAL,NBA,SG,35,1207,0.373,0.401,0.293,...,0.338,0.258,0.449,0.485,0.350,0.496,0.750,0.534,0.273,0.268
19,2015-16,37,LAL,NBA,SF,66,1863,0.358,0.410,0.285,...,0.252,0.420,0.452,0.491,0.354,0.502,0.757,0.541,0.276,0.285

In [101]:
df2 = df[["Season","Age","FG.1", "2P.1","3P.1", "eFG.1", "FT.1", "TS.1"]]

In [93]:
df2

     Season  Age   FG.1   2P.1   3P.1  eFG.1   FT.1   TS.1
0   2003-04   19  0.439  0.460  0.347  0.471  0.752  0.516
1   2004-05   20  0.447  0.470  0.356  0.482  0.756  0.529
2   2005-06   21  0.454  0.478  0.358  0.490  0.745  0.536
3   2006-07   22  0.458  0.485  0.358  0.496  0.752  0.541
4   2007-08   23  0.457  0.484  0.362  0.497  0.755  0.540
5   2008-09   24  0.459  0.485  0.367  0.500  0.771  0.544
6   2009-10   25  0.461  0.492  0.355  0.501  0.759  0.543
7   2010-11   26  0.459  0.487  0.358  0.498  0.763  0.541
8   2011-12   27  0.448  0.477  0.349  0.487  0.752  0.527
9   2012-13   28  0.453  0.483  0.359  0.496  0.753  0.535
10  2013-14   29  0.454  0.488  0.360  0.501  0.756  0.541
11  2014-15   30  0.449  0.485  0.350  0.496  0.750  0.534
12  2015-16   31  0.452  0.491  0.354  0.502  0.757  0.541
13  2016-17   32  0.457  0.503  0.358  0.514  0.772  0.552
14  2017-18   33  0.460  0.510  0.362  0.521  0.767  0.556
15  2018-19   34  0.461  0.520  0.355  0.524  0.766  0.560
16  2019-20   35  0.460  0.524  0.358  0.529  0.773  0.565
17  2020-21   36  0.466  0.530  0.367  0.538  0.778  0.572

In [94]:
df2[df2["Season"] == '2003-04'].values.tolist()[0][2:]

[0.439, 0.46, 0.347, 0.471, 0.752, 0.516]

In [98]:
df2.columns.values.tolist()[2:]

['FG.1', '2P.1', '3P.1', 'eFG.1', 'FT.1', 'TS.1']

In [79]:
df.columns.values.tolist()[]

['FG', '2P', '3P', 'eFG', 'FT', 'TS']